global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: enclave-targets
    static_configs:
      - targets:
          - app-server.enclave:9100
          - db-server.enclave:9187
          - cache.enclave:9121
