apiVersion: 1

datasources:
  - name: Redis-TimeSeries
    type: redis-datasource
    access: proxy
    url: redis:6379
    isDefault: true
    jsonData:
      client: standalone
      poolSize: 8
      timeout: 10
