global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:

  - job_name: "iato-kernel"
    static_configs:
      - targets: ["iato-kernel:8080"]
    metrics_path: /metrics

  - job_name: "kafka"
    static_configs:
      - targets: ["kafka:9092"]

  - job_name: "redis"
    static_configs:
      - targets: ["redis:6379"]

  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]

